Add logging of joint and motor accelerations in YarpRobotLoggerDevice
ami-iit/bipedal-locomotion-framework pull request #493
Opened 2022-01-05 13:33 UTC by isorrentino

This PR depends on  https://github.com/ami-iit/bipedal-locomotion-framework/pull/492

2022-01-07 09:45 UTC, prashanthr05 approved these changes
Thanks, @isorrentino. Approval to merge after PR https://github.com/ami-iit/bipedal-locomotion-framework/pull/492 is merged.

2022-01-07 10:04 UTC, GiulioRomualdi requested changes
I would avoid merging this PR since this code is going to be removed after https://github.com/ami-iit/bipedal-locomotion-framework/pull/487 You could rebase this code on top of #487 so we can merge it as soon as #487 is merged

2022-01-10 15:20 UTC, isorrentino commented
Done!

2022-01-10 16:05 UTC, GiulioRomualdi approved these changes

2022-01-10 16:05 UTC, merged