Add the possibility to update the contact list in the swing foot trajectory planner
ami-iit/bipedal-locomotion-framework pull request #637
Opened 2023-03-28 16:22 UTC by GiulioRomualdi

With this PR it will be possible to update the contact list in the `SwingFootTrajectoryPlanner`. 
If the contact list is not empty, we check if it is possible to update the list.  Given some limitations of the framework (mainly due to the SO3 trajectory generation) for the time being, we support only the two following cases:
- Given the current time instant, both the stored and the new contact lists must have an active contact at the same pose.
- If the contact is not active (swing phase) the next contact must satisfy the following two hypothesis
   1. the orientation of the next contact must be the same as the orientation of the next contact in the contact list stored in the class.
   2. the impact time of the next contact must be the same as the one of the next contact in the contact list stored in the class.

⚠️ Similar to https://github.com/ami-iit/bipedal-locomotion-framework/pull/624 `advance()` must be called before getting the output

@LoreMoretti you can directly use this class along with the MPC you developed 😄 (cc @traversaro)

2023-03-28 17:42 UTC, traversaro requested changes

2023-03-28 17:42 UTC, traversaro commented on src/Contacts/include/BipedalLocomotion/Contacts/Contact.h
> +    [[nodiscard]] bool isContactAtive(const std::chrono::nanoseconds& t) const;
```suggestion
    [[nodiscard]] bool isContactActive(const std::chrono::nanoseconds& t) const;
```

small typo

2023-03-28 19:25 UTC, GiulioRomualdi commented on src/Contacts/include/BipedalLocomotion/Contacts/Contact.h
> +    [[nodiscard]] bool isContactAtive(const std::chrono::nanoseconds& t) const;
Fixed thank you :)

2023-03-29 07:32 UTC, S-Dafarra approved these changes

2023-03-29 07:32 UTC, S-Dafarra commented on src/Planners/include/BipedalLocomotion/Planners/SwingFootPlanner.h
> +     * if the contact list contained stored the class is empty, then it is the first time the
```suggestion
     * If the contact list stored in the class is empty, then it is the first time the
```

2023-03-29 08:26 UTC, merged