Add last version of RobotDynamicsEstimator code used for the paper
ami-iit/bipedal-locomotion-framework pull request #731
Opened 2023-09-25 11:51 UTC by isorrentino

Hi @GiulioRomualdi @S-Dafarra, 
this PR wants to align the files of the `RobotDynamicsEstimator` library already merged in `master` with the last version used for the paper.

2023-10-18 12:48 UTC, GiulioRomualdi requested changes

2023-10-18 12:48 UTC, GiulioRomualdi commented on src/Estimators/include/BipedalLocomotion/RobotDynamicsEstimator/AccelerometerMeasurementDynamics.h
> +#endif // BIPEDAL_LOCOMOTION_ESTIMATORS_ACCELEROMETER_MEASUREMENT_DYNAMICS_H
```suggestion
#endif // BIPEDAL_LOCOMOTION_ESTIMATORS_ACCELEROMETER_MEASUREMENT_DYNAMICS_H

```

2023-10-18 12:48 UTC, GiulioRomualdi commented on src/Estimators/include/BipedalLocomotion/RobotDynamicsEstimator/ConstantMeasurementModel.h
> +#endif // BIPEDAL_LOCOMOTION_ESTIMATORS_CONSTANT_MEASUREMENT_MODEL_H
Can you add the a white line at the end of the file?

2023-10-19 09:47 UTC, isorrentino commented
@GiulioRomualdi I added the new line at the end of each file.

2023-10-19 10:14 UTC, GiulioRomualdi commented
Thank you @isorrentino. Let's wait for the CI

2023-10-19 10:15 UTC, GiulioRomualdi approved these changes

2023-10-19 11:05 UTC, merged