Implement `RobotDynamicsEstimatorDevice` - PR6
ami-iit/bipedal-locomotion-framework pull request #756
Opened 2023-11-08 10:06 UTC by isorrentino

2023-11-09 09:31 UTC, isorrentino commented
I rebased on master. The PR is ready for review @GiulioRomualdi

2023-11-09 14:22 UTC, GiulioRomualdi requested changes

2023-11-09 14:22 UTC, GiulioRomualdi commented on devices/RobotDynamicsEstimatorDevice/CMakeLists.txt
> +endif()
```suggestion
endif()

```

2023-11-09 14:22 UTC, GiulioRomualdi commented on devices/RobotDynamicsEstimatorDevice/app/CMakeLists.txt
> +endforeach ()
```suggestion
endforeach ()

```

2023-11-09 14:22 UTC, GiulioRomualdi commented on devices/RobotDynamicsEstimatorDevice/include/BipedalLocomotion/RobotDynamicsEstimatorDevice.h
> +#endif // BIPEDAL_LOCOMOTION_FRAMEWORK_ROBOT_DYNAMICS_ESTIMATOR_DEVICE_H
```suggestion
#endif // BIPEDAL_LOCOMOTION_FRAMEWORK_ROBOT_DYNAMICS_ESTIMATOR_DEVICE_H

```

2023-11-09 14:22 UTC, GiulioRomualdi commented on devices/RobotDynamicsEstimatorDevice/include/BipedalLocomotion/RobotDynamicsEstimatorDevice.h
> +/**
Can you document the class and the methods?

2023-11-09 14:22 UTC, GiulioRomualdi commented on devices/RobotDynamicsEstimatorDevice/src/RobotDynamicsEstimatorDevice.cpp
> +}
```suggestion
RobotDynamicsEstimatorDevice::~RobotDynamicsEstimatorDevice() = default;
```

2023-11-09 14:22 UTC, GiulioRomualdi commented on devices/RobotDynamicsEstimatorDevice/src/RobotDynamicsEstimatorDevice.cpp
> +        std::lock_guard<std::mutex> lockOutput(m_estimatorOutput.mutex);
I think you should indent this

2023-11-09 14:22 UTC, GiulioRomualdi commented on devices/RobotDynamicsEstimatorDevice/src/RobotDynamicsEstimatorDevice.cpp
> +}
```suggestion
}

```

2023-11-09 16:04 UTC, isorrentino commented
Suggestions applied and class documented.
@GiulioRomualdi

2023-11-09 16:05 UTC, isorrentino commented
I'm going to add the README. I'll let you know as soon as it is pushed.

2023-11-10 09:03 UTC, isorrentino commented
README added (actually yesterday). @GiulioRomualdi

2023-11-10 09:05 UTC, GiulioRomualdi approved these changes

2023-11-10 09:05 UTC, isorrentino commented
I just rebased on master

2023-11-10 10:07 UTC, merged