Adding time profiler to BLF.
ami-iit/bipedal-locomotion-framework pull request #826
Opened 2024-03-28 16:24 UTC by G-Cervettini

2024-03-29 08:09 UTC, S-Dafarra commented
Hi @G-Cervettini, please follow the modifications of https://github.com/robotology/walking-controllers/pull/164. We noticed that the ``clock`` function may give weird outputs.

2024-03-29 09:47 UTC, GiulioRomualdi requested changes
In addition to @S-Dafarra suggestions I add somethings

2024-03-29 09:47 UTC, GiulioRomualdi commented on src/CMakeLists.txt
> +add_subdirectory(TimeProfiler)
II would add it in system

2024-03-29 09:47 UTC, GiulioRomualdi commented on src/TimeProfiler/include/BipedalLocomotion/TimeProfiler/TimeProfiler.h
> +namespace BipedalLocomotion
```suggestion
namespace BipedalLocomotion
{
namespace System
{
```

2024-03-29 09:47 UTC, GiulioRomualdi commented on src/TimeProfiler/include/BipedalLocomotion/TimeProfiler/TimeProfiler.h
> +        const double& getAverageDuration() const;
Instead of return a double you should return std::chrono::nanoseconds

2024-03-29 09:47 UTC, GiulioRomualdi commented on src/TimeProfiler/src/TimeProfiler.cpp
> +        std::cout << infoStream << std::endl;
I would avoid to use cout you can use `log()->`

2024-03-30 11:59 UTC, GiulioRomualdi commented
Thank you @G-Cervettini, I applied the clang-format and removed the `std::cerr` from the code.

Thank you for spending time porting this feature in BLF ❤️

2024-03-30 12:00 UTC, merged