Implement low-pass filter for estimated friction torque
ami-iit/bipedal-locomotion-framework pull request #892
Opened 2024-09-20 16:25 UTC by isorrentino

This PR implements:
- a low-pass filter for filtering the estimated friction torque
- a saturation for the estimated friction torque

2024-09-23 15:06 UTC, GiulioRomualdi commented
Hi @isorrentino can you remove the white space?

2024-09-23 15:23 UTC, isorrentino commented
> Hi @isorrentino can you remove the white space?

Done

2024-09-23 19:54 UTC, GiulioRomualdi requested changes

2024-09-23 19:54 UTC, GiulioRomualdi commented on devices/JointTorqueControlDevice/include/BipedalLocomotion/JointTorqueControlDevice.h
> +    double max_output_friction; /**< maximum output of the friction model */
Can you use the style of the remaining part of the code?

2024-09-23 20:57 UTC, GiulioRomualdi commented
https://github.com/ami-iit/bipedal-locomotion-framework/pull/892/commits/9afee9a4aa01ead5dd0ff404fe9001a3c846f4c9 sob. I've fixed the changelog manually :(

2024-09-25 06:54 UTC, GiulioRomualdi approved these changes

2024-09-25 09:38 UTC, isorrentino commented
Hi @GiulioRomualdi I think the failure is not related to this PR

```
99% tests passed, 1 tests failed out of 149

Total Test time (real) = 630.17 sec

Errors while running CTest
The following tests FAILED:
	120 - memcheck_ArucoDetectorTestUnitTests (Failed)
Error: Process completed with exit code 8.
```

2024-09-25 13:10 UTC, merged